### ISSUE TITLE
Giving error when i set the min value to 0 nad max value to 10 it shows => Invariant Violation:inveriant Violation:inputRange must be monotonically non-decreasing 0, 33, 10

### ISSUE THREAD

**Issue by rahulsainiapptunix** [VitorCodes/react-native-motion-slider#1]

**Comment by akkravikumar** [comment]
Im also facing this same issue. Could you help to resolve this. @VitorCodes

**Comment by aalsa3** [comment]
I'm getting this issue when setting the backgroundColors

**Comment by aalsa3** [comment]
I found the solution.

In index.js under `setGradient()`:


`let currentRange = 0;`

should be

`let currentRange = min;`

**Comment by akkravikumar** [comment]
I used this https://github.com/akkravikumar/toggle-switch
