### ISSUE TITLE
Changing Min, Max numbers depending on scale

### ISSUE THREAD

**Issue by kchangch** [VitorCodes/react-native-motion-slider#2]
```
<View>
          <MotionSlider
            title={'Choose the desired temperature'}
            min={57}
            max={99}
            value={80}
            decimalPlaces={1}
            units={'º'}
            backgroundColor={[
              'rgb(3, 169, 244)',
              'rgb(255, 152, 0)',
              'rgb(255, 87, 34)'
            ]}
            onValueChanged={value => console.log(value)}
            onPressIn={() => console.log('Pressed in')}
            onPressOut={() => console.log('Pressed out')}
            onDrag={() => console.log('Dragging')}
          />
        </View>
```

I dont understand why my app keeps breaking if the value i have set is between the Min/Max. Any idea of how to fix it?

I'm getting "Invariant violation: inputRange must be monotonically non-decreasing 57,33,99"

**Comment by MoroniCallejas** [comment]
I have the same issue

**Comment by VitorCodes** [comment]
> ```
> <View>
>           <MotionSlider
>             title={'Choose the desired temperature'}
>             min={57}
>             max={99}
>             value={80}
>             decimalPlaces={1}
>             units={'º'}
>             backgroundColor={[
>               'rgb(3, 169, 244)',
>               'rgb(255, 152, 0)',
>               'rgb(255, 87, 34)'
>             ]}
>             onValueChanged={value => console.log(value)}
>             onPressIn={() => console.log('Pressed in')}
>             onPressOut={() => console.log('Pressed out')}
>             onDrag={() => console.log('Dragging')}
>           />
>         </View>
> ```
> 
> I dont understand why my app keeps breaking if the value i have set is between the Min/Max. Any idea of how to fix it?
> 
> I'm getting "Invariant violation: inputRange must be monotonically non-decreasing 57,33,99"

Thanks for reporting 🙂 this issue was also reported at #1 and should be fixed by now. The problem was in **setGradient** function inside src/index.js which had this line `currentRange = 0` and now was changed to `currentRange = min`.
